config/routes.rb
Sociorent::Application.routes.draw do



  get "item_history/index"

  mount RailsAdmin::Engine => '/cb_admin', :as => 'rails_admin'

  ActiveAdmin.routes(self)

  resources :static_pages

  get 'privacy_policy' => 'static_pages#privacypolicy'

  get 'page/:id' => 'static_pages#show'
  get 'college_ambassadors' => 'static_pages#colleges'

  # get 'aboutus' => 'static_pages#about_us'
  # get 'pricing' => 'static_pages#pricing'
  # get 'contactus' => 'static_pages#contactus'
  # get 'privacy_policy' => 'static_pages#privacypolicy'
  # get 'terms_of_use' => 'static_pages#termsofuse'

  get "home/index"
  match "/search" => "home#search"
  post "home/book_request"
  post "home/add_to_cart"
  post "home/remove_from_cart"
  post "/orders/create"
  match "/welcome" => "users#get_user_details"
  match "/get_bank_details/:id" => "home#get_bank_details"
  post "/users/save_user_details"
  post "/orders/rented_show_more"
  post "/orders/rented_college"
  post "users/update"
  post "users/add_to_wishlist"
  post "users/wishlist"
  post "users/remove_from_wishlist"
  post "home/get_adoption_rate"
  post "home/make_review"
  post "users/select_reference"
  post "orders/counter_cash_payment"
  post "home/apply_intership"
  match "update_shipping" => "home#update_shipping"
  post "home/load_more"
  match "book/details/:id" => "home#book"
  match "validate/:type" => "home#validate"
  match "print_invoice/:order"=>"orders#print_invoice"
  match "getSignature" =>"home#citrus_signature"
  match "/verify_code" => "orders#verify_code"
  match "/print_label" => "home#print_label"
  match "/print_invoice" => "home#print_invoice"
  match "/get_colleges" =>"users#get_colleges"
  match "/get_streams" => "users#get_streams"

  #matches #book/isbn
  get '/book/:isbn' => "home#book_deatils"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  namespace :ab_admin do
    post 'orders/new/fetch_amounts' => 'orders#fetch_amount'
    post 'orders/:id/edit' => 'orders#update'
    post 'orders/create' => 'orders#create'
  end

  devise_for :counters

  ##P2P Routes
  namespace :street do


    root :to => "index#index"



    match 'aboutus' => 'static_pages#aboutus'
    match 'contactus' => 'static_pages#contactus'
    match 'privacy_policy' => 'static_pages#privacypolicy'
    match 'how_to_sell' => 'static_pages#howtosell'
    match 'how_to_buy' => 'static_pages#howtobuy'
    match 'buyer_protection' => 'static_pages#buyerprotection'
    match 'terms_of_use' => 'static_pages#terms'
    match 'seller_policy' => 'static_pages#sellerpolicy'
    match 'buyer_policy' => 'static_pages#buyerpolicy'

    post '/profile/updateaddress' => 'users#updateaddress'

    resources :messages
    match 'mark_as_read' =>'messages#mark_as_read'
    resources :items
    resources :images
    resources :credits

    match 'profile' => 'users#profile'

    #for adimn
    scope 'admin' do
      #scaffold controller and view
      resources :categories ,:products ,:specs ,:service_pincodes , :item_deliveries , :cities ,:static_pages


      match 'staticpage' => "users#staticpages"
      match 'static_pages/get_page/:page_name' => 'static_pages#get_page'

      match 'cities/:id/destory' => 'cities#destroy'

      root :to => 'categories#index'
      match 'jobs(/:job(/:cmd))' => 'users#show_jobs'
    end

    scope 'mob' do
      match 'getcities' => 'mobile#get_city'
      match  'recentitems(/:cat(/:prod))' => 'mobile#recent_items'
      get '/query/:query/:city' => 'mobile#recent_items'
      match 'update_view_count/:id'=> "mobile#update_view_count"
    end

      match "/get_city/:q" => "index#get_city"
      match "sellers/:id/:name" => "index#seller_items"

      match 'gettemplate' => 'items#downloadtemplate'

#      get "categories/set_category" => "categories#set_category"
#      get "categories/sub_category" => "categories#sub_category"

      match 'getcategories' => "categories#getcategories"
      match 'getsubcategories/:id' => "categories#getsubcategories"

      get   'getbrand/:id' => "categories#get_brands"

      match 'getcities' => "cities#list"

      post 'users/list' => 'users#list'
      post 'users/verifymobile/code' => 'users#getcode'
      post 'users/verifymobile/:code' => 'users#verifycode'
      get  'paymentdetails(/:bought)' => 'users#paymentdetails'
      get  'paymentdetails/:type/:id(/:bought)' => 'item_deliveries#print_invoice_label'


      post 'location' => 'users#setlocation'
      post 'guesslocation' => 'users#guesslocation'

      get 'sellitem' => "items#new"
      post 'items/:id' => 'items#update'

      match 'getbook_details/:isbn13' => "items#getbook_details"
      get 'getserviceavailability/:itemid/:pincode' => 'service_pincodes#check_availability'


      get 'faileduploads' => 'users#failed_uploads'

      get 'getattributes/:id' => "categories#get_attributes"
      get 'getspec/:id' =>  "items#get_spec"
      get 'welcome' => 'users#welcome'
      post 'welcome' => 'users#user_first_time'

      match 'itempayment/:id' => 'items#sellitem_pricing'
      get 'delete/:id' => "items#destroy"

      post 'addimage/:item_id' => "items#add_image"
      get  'addimage/:form_id/form' => "items#sellitem_pricing"

      get 'sold/:id' => "items#sold"


      get 'mystore(/:query(/user/:id))' => 'items#inventory'

      get 'dashboard' => 'users#dashboard'
      match 'upload_csv/'=>'items#upload_csv'
      match 'approve(/:query)' => 'items#approve'
      match 'approve/user/:id' => 'items#approve'
      match 'disapprove' => 'items#disapprove'
      match 'disapprove/user/:id' => 'items#disapprove'
      match 'waiting(/user/:id)' => 'items#waiting'
      get  'favourites' => 'users#favouriteusers'
      post 'favourites' => 'users#setfavourite'
      post 'favourites/:id' => 'users#setfavourite'
      match 'vendors(/:cmd)' => 'users#vendorsdetails'
      match 'getusers(/:query)' => 'users#getusers'

      get 'getfailed/:type/:dte' => 'users#download_failed'
      #post 'payments' => 'users#userpayments'

      get 'getmessages(/:id)' => 'messages#getmessages'

      match 'search/q' => "index#search_query"

      match 'search/c/:ignore1/:cat(/:ignore2/:prod)' => "index#search_cat"

      match "search/:id" =>"index#search"
      #citruspay response catching
      match "getCitursSignature" => "items#get_citrus_signature"
      match "update_citrus" => "items#update_online_payment"
      match ":ignore1/:cat/filters(/*applied_filters)" =>"index#browse_filter" ,  :applied_filters => /[^\/]*/
      match ":ignore1/:cat/:ignore2/:prod/filters(/*applied_filters)" =>"index#browse_filter"  ,:applied_filters => /[^\/]*/

      # get ':cat/:prod/:item' => 'items#view' ,:as => :item_url
      get ':ignore1/:cat/:ignore2/:prod/:item/:id' => 'items#view' ,:as => :item_url
      get ':ignore1/:cat(/:ignore2/:prod)' => "index#browse"
      match "update_shipping_address" => "users#update_shipping"
  end


  root :to => 'home#index'

  match '/system/*a', :to => 'errors#ignore_routing'
  match '/assets/*a', :to => 'errors#ignore_routing'

  match '*a', :to => 'errors#routing'

end

app/controllers/street/categories_controller.rb
class Street::CategoriesController < ApplicationController

 layout :p2p_layout

   before_filter :p2p_user_signed_in

  # GET /p2p/categories
  # GET /p2p/categories.json
  def index
    @p2p_categories = P2p::Category.order('priority')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @p2p_categories }
    end
  end

  # GET /p2p/categories/1
  # GET /p2p/categories/1.json
  def show
    @p2p_category = P2p::Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @p2p_category }
    end
  end

  # GET /p2p/categories/new
  # GET /p2p/categories/new.json
  def new
    @p2p_category = P2p::Category.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @p2p_category }
    end
  end

  # GET /p2p/categories/1/edit
  def edit
    @p2p_category = P2p::Category.find(params[:id])
  end

  # POST /p2p/categories
  # POST /p2p/categories.json
  def create
    @p2p_category = P2p::Category.new(params[:p2p_category])

    respond_to do |format|
      if @p2p_category.save

                 redirect_to street_categories_url, notice: 'Category was successfully created.'
                 return

        format.html { redirect_to @p2p_category, notice: 'Category was successfully created.' }
        format.json { render json: @p2p_category, status: :created, location: @p2p_category }
      else
        format.html { render action: "new" }
        format.json { render json: @p2p_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /p2p/categories/1
  # PUT /p2p/categories/1.json
  def update
    @p2p_category = P2p::Category.find(params[:id])


    respond_to do |format|
      if @p2p_category.update_attributes(params[:p2p_category])

        redirect_to street_categories_url, notice: 'Category was successfully created.'
        return

        format.html { redirect_to @p2p_category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @p2p_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /p2p/categories/1
  # DELETE /p2p/categories/1.json
  def destroy
    @p2p_category = P2p::Category.find(params[:id])
    @p2p_category.destroy

    respond_to do |format|
      format.html { redirect_to street_categories_url }
      format.json { head :no_content }
    end
  end



  # get the categories for listing in xeditable
  def getcategories
    @res = []
    P2p::Category.all.each do |c|
      next if  !c.category.nil? or  c.specs.size == 0
      @res << {:value => c.id, :text => c.name}
    end
    render :json => @res
  end

  # get the categories for listing in xeditable
  def getsubcategories
    @res = []
    P2p::Category.where("category_id = #{params[:id]}").each do |c|
      next if c.specs.size == 0
      @res << {:value => c.id, :text => c.name}
    end
    render :json => @res
  end

  # for new item
  def get_attributes
    cat = P2p::Category.find(params[:id])
    @attributes = cat.specs.select("id,name,display_type,placeholder").order(:id)
    #  render :json => @attr
  end

  def get_brands
    cat =P2p::Category.find(params[:id])
    brand  = cat.products.select("id as value,name as text")
    brand << "Other"
    render :json => brand
    return
  end

end

app/controllers/street/cities_controller.rb
class Street::CitiesController < ApplicationController

  layout :p2p_layout

  # GET /p2p/cities
  # GET /p2p/cities.json
  def index
    response={:aaData => []}
    #where to start
    if params.has_key?("iDisplayStart")
      start = (params[:iDisplayStart].to_i / params[:iDisplayLength].to_i) + 1
    else
      start = 1
    end
    #order by the time by default
    order = "updated_at desc"

    #if sort is explicitly sennt from the client
    if params.has_key?(:iSortCol_0)
      case params[:iSortCol_0]
      when "1" #based on sender column
        #check the table and sent the order by
          order = "name " + params[:sSortDir_0]
        #based on item
      end
    end

    if params[:searchq]
      cities = P2p::City.where("name like '%#{params[:searchq]}%'").paginate(:page => start,:per_page =>  params[:iDisplayLength] )
    else
      cities = P2p::City.paginate(:page => start,:per_page =>  params[:iDisplayLength] )
    end

    # form the response for the datatable
    response[:iTotalRecords] =  cities.count
    response[:iTotalDisplayRecords] = cities.count
    
    #form the time to be displayed
    cities.each do |city|
      response[:aaData].push({
                                 "0" => city.name,
                                 "1" => city.show_city,
                                 "2" => "<a href='/street/admin/cities/#{city.id}/edit'><i class='icon-edit'></i></a> <a href='/street/admin/cities/#{city.id}/destory'><i class='icon-trash'></i></a>".html_safe


      })
    end
    if request.xhr?
      render :json => response
    end
  end

  # GET /p2p/cities/1
  # GET /p2p/cities/1.json
  def show
    @p2p_city = P2p::City.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @p2p_city }
    end
  end

  # GET /p2p/cities/new
  # GET /p2p/cities/new.json
  def new
    @p2p_city = P2p::City.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @p2p_city }
    end
  end

  # GET /p2p/cities/1/edit
  def edit
    @p2p_city = P2p::City.find(params[:id])
  end

  # POST /p2p/cities
  # POST /p2p/cities.json
  def create
    @p2p_city = P2p::City.new(params[:p2p_city])

    respond_to do |format|
      if @p2p_city.save
        format.html { redirect_to '/street/admin/cities', notice: 'City was successfully created.' }
        format.json { render json: @p2p_city, status: :created, location: @p2p_city }
      else
        format.html { render action: "new" }
        format.json { render json: @p2p_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /p2p/cities/1
  # PUT /p2p/cities/1.json
  def update
    @p2p_city = P2p::City.find(params[:id])

    respond_to do |format|
      if @p2p_city.update_attributes(params[:p2p_city])
        format.html { redirect_to '/street/admin/cities', notice: 'City was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @p2p_city.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /p2p/cities/1
  # DELETE /p2p/cities/1.json
  def destroy
    @p2p_city = P2p::City.find(params[:id])
    @p2p_city.destroy

    respond_to do |format|
      format.html { redirect_to street_cities_url }
      format.json { head :no_content }
    end
  end

  # get the city list for xeditable
  def list
    unless params[:query].nil?
      # if some how we have empty city name empyt in database  ignore it
  	  cities = P2p::City.select('name').where("name like '" + params[:query] + "%' or name is not null and show_city = 1")
    else
      cities = P2p::City.select('name').where(:show_city => true)
    end

  	if cities.nil?
  		cities[0] = [{:name =>'No Result'}]
  	end

  	render :json => cities.collect{|city| city.name =((city.name.nil?)  ? "" : city.name) ; {city.name  => city.name}}
  end
end

app/controllers/street/credits_controller.rb
class Street::CreditsController < ApplicationController

   before_filter :p2p_user_signed_in ,:except => [:view]

   #check for user presence inside p2p
   before_filter :check_p2p_user_presence

   layout :p2p_layout

  def new
   @user=p2p_current_user
   @credit=@user.credits.new

  end

  def create
   @user=p2p_current_user
   @credit = @user.credits.new(params['p2p_credit'])
   if @credit.save
   	render :list
   else
    render :new
   end

  end

  def delete
    @user=p2p_current_user
     credit=@user.credits.find(params[:id])
     newcredit=credit.available
     credit.update_attributes(:available=>newcredit-1)
  end

  def list
  	@user=p2p_current_user

     @credit= @user.credits
       respond_to do |format|
        format.js
        end

  end
end

app/controllers/street/images_controller.rb
class Street::ImagesController < ApplicationController

	before_filter :p2p_user_signed_in

   #check for user presence inside p2p
   before_filter :check_p2p_user_presence

	layout :p2p_layout

	def destroy
		begin
			img = P2p::Image.find(params[:id])
		rescue
			render :json => {:status => "0"}
			return
		end

		img.img = nil
		img.destroy

		render :json => {:status => "1"}

	end
end

app/controllers/street/item_history_controller.rb
class Street::ItemHistoryController < ApplicationController

	layout :p2p_layout

  def index

  end


end
 

app/controllers/street/static_pages_controller.rb
class Street::StaticPagesController < ApplicationController

  layout :p2p_layout

  def new
    @page = StaticPage.new
  end

  def create
    page = StaticPage.create(params[:static_page])
  end

  def edit
    @page = StaticPage.find(params[:id])
  end


  def update
    @page = StaticPage.find(params[:id])
    @page = @page.update_attributes(params[:static_page])
  end

  def get_page
    @page = StaticPage.find_by_page_name(params[:page_name])
    render :json => @page
  end


  def aboutus
    @page = StaticPage.find_by_page_name('p2p_aboutus')
    render :getpage
  end

  def contactus
    @page = StaticPage.find_by_page_name('p2p_contactus')
    render :getpage
  end

  def privacypolicy
    @page = StaticPage.find_by_page_name('p2p_privacypolicy')
    render :getpage
  end

  def howtosell
    @page = StaticPage.find_by_page_name('p2p_how_to_sell')
    render :getpage
  end

  def howtobuy
    @page = StaticPage.find_by_page_name('p2p_how_to_buy')
    render :getpage
  end

  def buyerprotection
    @page = StaticPage.find_by_page_name('p2p_buyer_protection')
    render :getpage
  end

  def terms
    @page = StaticPage.find_by_page_name('p2p_terms_conditions')
    render :getpage
  end

  def sellerpolicy
    @page = StaticPage.find_by_page_name('p2p_seller_policy')
    render :getpage
  end

  def buyerpolicy
    @page = StaticPage.find_by_page_name('p2p_buyer_policy')
    render :getpage
  end

  def show
    @page = StaticPage.find_by_page_name(params[:id])
  end
  
end

app/helpers/p2p/item_deliveries_helper.rb
module P2p::ItemDeliveriesHelper
end

app/helpers/street/mobile_helper.rb
module Street::MobileHelper
end

app/views/street/item_deliveries/_form.html.erb
<% url = (@p2p_item_delivery.new_record?) ? street_item_deliveries_path : street_item_delivery_path(@p2p_item_delivery) %>

<%= simple_form_for(@p2p_item_delivery ,:url => url) do |f| %>
  <%= f.error_notification %>

  <% (@p2p_item_delivery.shipping_date = @p2p_item_delivery.shipping_date.strftime("%m/%d/%Y") ) unless @p2p_item_delivery.shipping_date.nil? %>
  
  <% (@p2p_item_delivery.delivery_date = @p2p_item_delivery.delivery_date.strftime("%m/%d/%Y") )  unless @p2p_item_delivery.delivery_date.nil? %>

  <div class="form-inputs">




<% if session[:isadmin]  or @p2p_item_delivery.item.user.id == session[:userid] %>

    <div class="control-group">

      <div class="controls">
        <%= f.input :courier_name %>
      </div>

    </div>


    <div class="control-group">

      <div class="controls">
        <%= f.input :tracking_no %>
      </div>

    </div>

    <div class="control-group">

      <%= f.label :shipping_date %>
      <div class="controls">
        <%= f.input :shipping_date , as: :string, input_html:{ class: 'datepicker' }, :include_blank => true,:label=>false%>
      </div>

    </div>

  <% if session[:isadmin] %>

    <div class="control-group">

        <%= f.label :shipping_charge %>
        <div class="controls">
          <%= f.number_field :shipping_charge %>
        </div>

    </div>

  <% end %>

<% end %>

<% if session[:isadmin]  or @p2p_item_delivery.buyer.id == session[:userid] %>

 	<div class="control-group">

      <%= f.label :delivery_date %>
  		<div class="controls">
  			<%= f.input :delivery_date ,as: :string, input_html:{ class: 'datepicker' },:include_blank => true,:label=>false %>
  		</div>

  	</div>

 </div>

<% end %>



<% if session[:isadmin] %>

  <div class="control-group">

      <%= f.label :commission %>
      <div class="controls">
        <%= f.number_field :commission %>
      </div>

  </div>

<% end %>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>

<% end %>

app/views/street/item_deliveries/edit.html.erb
<% content_for :pagetitle  do %>
    Payments
<%end %>


<div class="row" id="body_content" >

     <div class="span3">

      <ul class="nav nav-list">

        <%= render "/street/users/dashboard_menu.html.erb" %>
        <%#= render "/p2p/index/scat_menu" %>

      </ul>
    </div>

		<div class="span9">

			<h3>Updating <%= @p2p_item_delivery.item.title %> </h3>

      <%= link_to raw('<i class="icon-arrow-left"></i> Back'), street_item_deliveries_path, class: "pull-right btn" %>


			<%= render 'form' %>

			
		</div>
</div>

app/views/street/item_deliveries/index.html.erb
<% content_for :pagetitle  do %>
    Payments
<%end %>


<div class="row" id="body_content" >

     <div class="span3">

      <ul class="nav nav-list">

        <%= render "/street/users/dashboard_menu.html.erb" %>
        <%#= render "/p2p/index/scat_menu" %>

      </ul>
    </div>

<div class="span9">
            <h1>Payment Details</h1>
            <% if @p2p_item_deliveries.count > 0 %>
            <%= will_paginate(@p2p_item_deliveries , :renderer => BootstrapPagination::Rails) %>
            <table class="table table-striped table-bordered ">
              <tr>
                <th>Item ID</th>
                <th>User Email</th>
                <th>TXN ID</th>
                <th>Courier Name</th>
                <th>Tracking Num</th>
                <th>Shipping Date</th>
                <th>Deleviry Date</th>
                <th>Commission</th>
                <th>Shipping Charge</th>
                <th>Citrus pay ID</th>
                <th>Citrus Pay reason</th>
                <th>Citrus Ref no</th>
                <th>Actions</th>

              </tr>

            <% @p2p_item_deliveries.each do |p2p_item_delivery| %>
              <tr>
                <td><%= p2p_item_delivery.item.id %></td>
                <td><%= p2p_item_delivery.buyer.user.email %><br/><%=p2p_item_delivery.buyer.user.name%><br/><i class="icon-mobile-phone"></i> <%=p2p_item_delivery.buyer.user.mobile_number%></td>
                <td><%= p2p_item_delivery.txn_id %></td>
                <td><%= p2p_item_delivery.courier_name %></td>
                <td><%= p2p_item_delivery.tracking_no %></td>
                <td><%= p2p_item_delivery.shipping_date.strftime("%d-%b-%C%y") unless p2p_item_delivery.shipping_date.nil?%></td>
                <td><%=  p2p_item_delivery.delivery_date.strftime("%d-%b-%C%y") unless p2p_item_delivery.delivery_date.nil?  %></td>
                <td><%= p2p_item_delivery.commission %></td>
                <td><%= p2p_item_delivery.shipping_charge %></td>

                <td><%= p2p_item_delivery.citrus_pay_id %></td>
                <td><%= p2p_item_delivery.citrus_reason %></td>
                <td><%= p2p_item_delivery.citrus_ref_no %></td>


    <td><%#= link_to 'Show', p2p_item_delivery %>
    <%= link_to '<i class="icon-edit"></i>'.html_safe, edit_street_item_delivery_path(p2p_item_delivery) %>
    </td>

              </tr>
            <% end %>
            </table>


            <%= will_paginate(@p2p_item_deliveries , :renderer => BootstrapPagination::Rails) %>
            <br />
            <% else %>
                <h5> No payments done Yet !!</h5>
            <% end %>

            <%#= link_to 'New Item delivery', new_p2p_item_delivery_path %>

</div>
</div>

app/views/street/item_deliveries/new.html.erb
<h1>New p2p_item_delivery</h1>

<%= render 'form' %>

<%= link_to 'Back', p2p_item_deliveries_path %>