config/routes.rb
Sociorent::Application.routes.draw do



  get "item_history/index"

  mount RailsAdmin::Engine => '/cb_admin', :as => 'rails_admin'

  ActiveAdmin.routes(self)

  resources :static_pages

  get 'privacy_policy' => 'static_pages#privacypolicy'

  get 'page/:id' => 'static_pages#show'
  get 'college_ambassadors' => 'static_pages#colleges'

  # get 'aboutus' => 'static_pages#about_us'
  # get 'pricing' => 'static_pages#pricing'
  # get 'contactus' => 'static_pages#contactus'
  # get 'privacy_policy' => 'static_pages#privacypolicy'
  # get 'terms_of_use' => 'static_pages#termsofuse'

  get "home/index"
  match "/search" => "home#search"
  post "home/book_request"
  post "home/add_to_cart"
  post "home/remove_from_cart"
  post "/orders/create"
  match "/welcome" => "users#get_user_details"
  match "/get_bank_details/:id" => "home#get_bank_details"
  post "/users/save_user_details"
  post "/orders/rented_show_more"
  post "/orders/rented_college"
  post "users/update"
  post "users/add_to_wishlist"
  post "users/wishlist"
  post "users/remove_from_wishlist"
  post "home/get_adoption_rate"
  post "home/make_review"
  post "users/select_reference"
  post "orders/counter_cash_payment"
  post "home/apply_intership"
  match "update_shipping" => "home#update_shipping"
  post "home/load_more"
  match "book/details/:id" => "home#book"
  match "validate/:type" => "home#validate"
  match "print_invoice/:order"=>"orders#print_invoice"
  match "getSignature" =>"home#citrus_signature"
  match "/verify_code" => "orders#verify_code"
  match "/print_label" => "home#print_label"
  match "/print_invoice" => "home#print_invoice"
  match "/get_colleges" =>"users#get_colleges"
  match "/get_streams" => "users#get_streams"

  #matches #book/isbn
  get '/book/:isbn' => "home#book_deatils"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/users/auth/:provider' => 'users/omniauth_callbacks#passthru'
  end

  namespace :ab_admin do
    post 'orders/new/fetch_amounts' => 'orders#fetch_amount'
    post 'orders/:id/edit' => 'orders#update'
    post 'orders/create' => 'orders#create'
  end

  devise_for :counters

  ##P2P Routes
  namespace :street do


    root :to => "index#index"



    match 'aboutus' => 'static_pages#aboutus'
    match 'contactus' => 'static_pages#contactus'
    match 'privacy_policy' => 'static_pages#privacypolicy'
    match 'how_to_sell' => 'static_pages#howtosell'
    match 'how_to_buy' => 'static_pages#howtobuy'
    match 'buyer_protection' => 'static_pages#buyerprotection'
    match 'terms_of_use' => 'static_pages#terms'
    match 'seller_policy' => 'static_pages#sellerpolicy'
    match 'buyer_policy' => 'static_pages#buyerpolicy'

    post '/profile/updateaddress' => 'users#updateaddress'

    resources :messages
    match 'mark_as_read' =>'messages#mark_as_read'
    resources :items
    resources :images
    resources :credits

    match 'profile' => 'users#profile'

    #for adimn
    scope 'admin' do
      #scaffold controller and view
      resources :categories ,:products ,:specs ,:service_pincodes , :item_deliveries , :cities ,:static_pages


      match 'staticpage' => "users#staticpages"
      match 'static_pages/get_page/:page_name' => 'static_pages#get_page'

      match 'cities/:id/destory' => 'cities#destroy'

      root :to => 'categories#index'
      match 'jobs(/:job(/:cmd))' => 'users#show_jobs'
    end

    scope 'mob' do
      match 'getcities' => 'mobile#get_city'
      match  'recentitems(/:cat(/:prod))' => 'mobile#recent_items'
      get '/query/:query/:city' => 'mobile#recent_items'
      match 'update_view_count/:id'=> "mobile#update_view_count"
    end

      match "/get_city/:q" => "index#get_city"
      match "sellers/:id/:name" => "index#seller_items"

      match 'gettemplate' => 'items#downloadtemplate'

#      get "categories/set_category" => "categories#set_category"
#      get "categories/sub_category" => "categories#sub_category"

      match 'getcategories' => "categories#getcategories"
      match 'getsubcategories/:id' => "categories#getsubcategories"

      get   'getbrand/:id' => "categories#get_brands"

      match 'getcities' => "cities#list"

      post 'users/list' => 'users#list'
      post 'users/verifymobile/code' => 'users#getcode'
      post 'users/verifymobile/:code' => 'users#verifycode'
      get  'paymentdetails(/:bought)' => 'users#paymentdetails'
      get  'paymentdetails/:type/:id(/:bought)' => 'item_deliveries#print_invoice_label'


      post 'location' => 'users#setlocation'
      post 'guesslocation' => 'users#guesslocation'

      get 'sellitem' => "items#new"
      post 'items/:id' => 'items#update'

      match 'getbook_details/:isbn13' => "items#getbook_details"
      get 'getserviceavailability/:itemid/:pincode' => 'service_pincodes#check_availability'


      get 'faileduploads' => 'users#failed_uploads'

      get 'getattributes/:id' => "categories#get_attributes"
      get 'getspec/:id' =>  "items#get_spec"
      get 'welcome' => 'users#welcome'
      post 'welcome' => 'users#user_first_time'

      match 'itempayment/:id' => 'items#sellitem_pricing'
      get 'delete/:id' => "items#destroy"

      post 'addimage/:item_id' => "items#add_image"
      get  'addimage/:form_id/form' => "items#sellitem_pricing"

      get 'sold/:id' => "items#sold"


      get 'mystore(/:query(/user/:id))' => 'items#inventory'

      get 'dashboard' => 'users#dashboard'
      match 'upload_csv/'=>'items#upload_csv'
      match 'approve(/:query)' => 'items#approve'
      match 'approve/user/:id' => 'items#approve'
      match 'disapprove' => 'items#disapprove'
      match 'disapprove/user/:id' => 'items#disapprove'
      match 'waiting(/user/:id)' => 'items#waiting'
      get  'favourites' => 'users#favouriteusers'
      post 'favourites' => 'users#setfavourite'
      post 'favourites/:id' => 'users#setfavourite'
      match 'vendors(/:cmd)' => 'users#vendorsdetails'
      match 'getusers(/:query)' => 'users#getusers'

      get 'getfailed/:type/:dte' => 'users#download_failed'
      #post 'payments' => 'users#userpayments'

      get 'getmessages(/:id)' => 'messages#getmessages'

      match 'search/q' => "index#search_query"

      match 'search/c/:ignore1/:cat(/:ignore2/:prod)' => "index#search_cat"

      match "search/:id" =>"index#search"
      #citruspay response catching
      match "getCitursSignature" => "items#get_citrus_signature"
      match "update_citrus" => "items#update_online_payment"
      match ":ignore1/:cat/filters(/*applied_filters)" =>"index#browse_filter" ,  :applied_filters => /[^\/]*/
      match ":ignore1/:cat/:ignore2/:prod/filters(/*applied_filters)" =>"index#browse_filter"  ,:applied_filters => /[^\/]*/

      # get ':cat/:prod/:item' => 'items#view' ,:as => :item_url
      get ':ignore1/:cat/:ignore2/:prod/:item/:id' => 'items#view' ,:as => :item_url
      get ':ignore1/:cat(/:ignore2/:prod)' => "index#browse"
      match "update_shipping_address" => "users#update_shipping"
  end


  root :to => 'home#index'

  match '/system/*a', :to => 'errors#ignore_routing'
  match '/assets/*a', :to => 'errors#ignore_routing'

  match '*a', :to => 'errors#routing'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @user=current_user
    if @user
      # check if user has mobile ,college, stream
      if @user.mobile_number.nil? || @user.college.nil? || @user.stream.nil?
        redirect_to "/welcome"
        return
      end
      # cart of the user
      cart = @user.cart
      @cart = cart.books if cart
      if session[:sociorent_cart_books_to_rent]
        @cart << Book.find(session[:sociorent_cart_books_to_rent].to_i)
        cart.save
        session[:sociorent_cart_books_to_rent] = nil
      end

      # list of colleges and stream for my account
      @college_names = College.pluck(:name)
      @streams = Stream.pluck(:name)
      # Intelligent Books
      # Using FB friends
      @search = intelligent_books(@user)
      if @search.count == 0
        @search = Book.first(6)
        @load_more = false
      elsif @search.count <= 6
        @load_more = false
      else
        @search = @search.first(6)
        @load_more = true
      end
      # orders made by the user
      @orders = @user.orders
      #referrals by ambassador
      unless @user.ambassador_manager.nil?
        @users_of_ambassador = Hash.new
        @ambassador = @user.ambassador_manager
        @ambassador.colleges.includes(:users).each do |college|
          # college ambassador count is one and ambassador should not be included
          if college.ambassadors.count == 1
            @users_of_ambassador[college.name] = college.users.where("id <>?",@user.id)
          elsif college.ambassadors.count > 1
            @users_of_ambassador[college.name] = @ambassador.users
          end
        end
      end

      # companies for internship
      @companies = Company.all
  		# render inner when user is logged in
  		render "inner"
    elsif @counter = current_counter
      render "counter"
  	else
      # check for params of isbn
      if params[:isbn]
        @search = Book.where(:isbn10 => params[:isbn]).first
      end
      #@images = General.first.images
  		render "index"
  	end
  end

  def search
    resp = {}

    # return if not xh
    unless request.xhr?
      redirect_to ''
      return
    end

    if params[:query] == ""
        if current_user.nil? #no method error college for nil class in intelligen books action
          @books = intelligent_books(current_user)
          @books += Book.first(6-@books.count) if @books.count < 6
        else
          @books = Book.first(6)
        end
    else
  	  @books = Book.search "#{params[:query]}", :star => true, :condition => "publisher_id is NOT NULL"
      # unless params[:query].=~ /^[0-9]+$/
      #   resp[:suggestion] = params[:query]
      #   if @books.suggestion? && @books.count <= 0
      #     resp[:suggestion] = @books.suggestion
      #     @books = Book.search @books.suggestion, :star => true
      #   end
      # end

      # @books.each_with_weighting do |result, weight|
      #   puts "%%%%%%%%%%%%%%%%%%%%%%%%%%"
      #   puts result
      #   puts "%%%%%%%%%%%%%%%%%%%%%%%%%%"
      #   puts weight
      #   puts "%%%%%%%%%%%%%%%%%%%%%%%%%%"
      # end
     end

    # @books.delete(nil)
    if @books.count > 6
      resp[:load_more] = true
    else
      resp[:load_more] = false
    end

    @books = @books.first(6)

     resp[:books] = @books.to_json(:include => :publisher)

    render :json => resp.to_json()

  end

  def load_more
    resp = {}
    load_more_count = params[:load_more_count].to_i * 6
    load_more_limit = load_more_count + 6
    unless params[:query] == ""
      query = "#{params[:query]}"
      @books = Book.search query, :condition => "publisher_id is NOT NULL"
      resp[:suggestion] = query
      # if @books.suggestion? && @books.count <= 0
      #   resp[:suggestion] = @books.suggestion
      #   @books = Book.search @books.suggestion, :star => true
      # end
    else
      @books = intelligent_books(current_user)
    end
    @books.delete(nil)
    if @books.count > load_more_limit
      resp[:load_more] = true
    else
      resp[:load_more] = false
    end
    books_to_send = @books[load_more_count, 6]
    resp[:books] = books_to_send.to_json(:include => :publisher)
    render :json => resp
  end

  def book_request
    user = current_user
    user.requests.create(:title => params[:title], :author => params[:author], :isbn => params[:isbn])
    render :text => "Your request was submitted, Thank you."
  end

  def add_to_cart
    # getting common variables
    book = Book.find(params[:book].to_i)
    user = current_user
    if user
      cart = user.cart
      # add book to the cart
      cart.books << book unless cart.books.include?(book)
      cart.save
      render :json => book.to_json(:include => :publisher)
    else
      session[:sociorent_cart_books_to_rent] = book.id
      render :nothing => true
    end
  end

  def remove_from_cart
    # getting common variables
    book = Book.find(params[:book].to_i)
    user = current_user
    cart = user.cart
    # remove book from cart
    book_cart = cart.book_carts.where(:book_id => book).first
    book_cart.delete if book_cart
    render :json => book.to_json(:include => :publisher)
  end

  def get_adoption_rate

     user = current_user
     @book = Book.find(params[:book].to_i)
     resp = []

     review_resp = []


    review_resp = JSON.parse @book.reviews.to_json(:include => {:user => {:only => :name}})
    # check if current user is allowed to make a review for this book
    resp << review_resp
    #resp << class_adoption_resp
    render :json => resp.to_json()
  end

  def make_review
    user = current_user
    book = Book.find(params[:book].to_i)
    review = user.reviews.create(:content => CGI.escapeHTML(params[:content]), :book_id => book.id, :semester => params[:semester])
    render :json => review.to_json(:include => {:user => {:only => :name}})
  end

  def apply_intership
    user = current_user
    company = Company.find(params[:company_id].to_i)
    company.company_users.create(:user_id => user.id)
    render :nothing => true
  end

  def update_shipping
    user=current_user
    resp = {}
    if user.update_attributes(:address=>params.except(:controller, :action).to_json)
      resp[:text] = "success"
      resp[:user] = user.to_json(:include => {:college => {:only => :name}, :stream => {:only => :name}})
    else
      resp[:text] = "failed"
    end
    render :json => resp
  end

  def get_bank_details
    bank=Bank.find(params[:id])
    render :text=> bank.details
  end

  def book
    @book = Book.find(params[:id])
    @book_image = "http://www.sociorent.com" + ((@book.images.first.nil?) ? "/assets/Sociorent.png" : @book.images.first.image.url).to_s
    render "book", :layout => false
  end

  def validate
    res=false
    case params[:type]
      when "email"
        res="true" if(User.where(:email=>params[:user]["email"]).count==0)
      when "mobile"
        res="true" if(User.where(:mobile_number=>params[:mobile]).count==0)
      when "mobile_number"
        res="true" if(User.where(:mobile_number=>params[:mobile_number]).count==0)
        if current_user.mobile_number == params[:mobile_number]
          res="true"
        end
    end
    if params[:reverse]
      res=(res=="true") ? "false" : "true"
    end
    render :text=> res and return
  end

  # function for setting citrus signature parameter for ajax call
  def citrus_signature
    require 'openssl'
    merchant_secret_key="d8d6f0e50ba34b74f5e82e26e9d321531ef6619b"
    random = 0
    if params[:item_id]
      unique = 0

      item = P2p::Item.find(params[:item_id])
      order_amount = item.price
      until unique == 1
        r = Random.new
        random = r.rand(1000000..9999999)
        if P2p::ItemDelivery.where(:txn_id=>random).count == 0
          unique =1
          address = {}
          params.each_with_index do |(name,value),index|
            unless name.to_s.index("address").nil?
              address["#{name}"] = value
            end
          end
          address = address.to_json()
          if item.paytype = 3
            item.item_deliveries.create(:txn_id=>random,:buyer => p2p_current_user,:commission => item.category.commission ,:shipping_charge => item.category.courier_charge,:shipping_address => address)
          else
            item.item_deliveries.create(:txn_id=>random,:buyer => p2p_current_user,:commission => item.category.commission ,:shipping_charge => 0, :shipping_address=>address )
          end

        end
      end
      params[:orderAmount] = order_amount
      params[:merchantTxnId] = random
    end

    sign_text = "#{params[:merchantId]}#{params[:orderAmount]}#{params[:merchantTxnId]}#{params[:currency]}"

    # creating HMAC sha1 signature with secret key
    digest  = OpenSSL::Digest::Digest.new('sha1')
    signature = OpenSSL::HMAC.hexdigest(digest, merchant_secret_key, sign_text)
    if params[:item_id]
      render :text=> {"signature" =>signature,"txn_id"=>random ,"time" => (Time.now.to_i * 3000)}.to_json()
    else
      render :text=>signature
    end
  end

  def print_label
    @order=Order.find(params[:order])
    shipped_date = params[:date] || Time.now
    @shipped = @order.book_orders.where("shipped_date=?",shipped_date.to_datetime().getutc)
    @shipped_amount = @shipped.inject(0) {|sum, hash| sum + hash.book.price} #=> 30
    @total_amount = @order.deposit_total
    if @total_amount < 1000
      @order.book_orders.where("shipped_date IS NOT NULL").order("shipped_date").limit(1).each do |current_order|
        if current_order.shipped_date == shipped_date.to_datetime().getutc
          @shipped_amount += 50
          @shipping_added = true
        end
      end
    end
    render "print_label", :layout=>false
  end



  def book_deatils


    unless params[:isbn].nil?

     user = current_user
     book = Book.find_by_isbn13(params[:isbn])


    book1 = Book.find(book.id)

    review_resp = JSON.parse book1.reviews.to_json(:include => {:user => {:only => :name}})


     resp ={

app/helpers/home_helper.rb
module HomeHelper
	def resource_name
    :user
  end

  def resource_class
  	"User"
  end
 
  def resource
    @resource ||= User.new
  end
 
  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end
end

app/views/home/_book_details_box.html.erb
<div id="book_details_box" class="font-dialog"></div>

app/views/home/_book_details_template.html.erb
<script type="script/template" id="book_details_template">
	
	<div class="book_heading"><%%= name %> <small><i>by</i> <%%= author %></small></div>
	<div class="left">
		
		<div class="book_image">
			<img src="<%%= book_image %>"/>
		</div>	
		<div class="auther_edition">
			<div class="edition"><b><%%= edition %></b></div>
			<div class="author">Author(s): <p><span class="blue author_names"></span></p></div>
			<div class="add_to_wishlist">Add to my Wishlist</div>
		</div>
		<div class="clear"></div>
		
		<!--<div class="socio_rent_rank">
			<div class="socio_rent_rank_left">
				SocioRent Rank
			</div>
			<div class="socio_rent_rank_right">
				<span class="blue"><%%= rank %>%</span>
			</div>
			<div class="clear"></div>
		</div>-->

	</div>
	<div class="right">
		<div class="information information_price">
			<div class="information_left"><b>list price</b></div>
			<div class="information_right"><b>Rs.<%%= price %></b></div>
			<div class="clear"></div>
			<div class="information_left"><b>rent</b></div>
			<div class="information_right"><b>Rs.<%%= Math.ceil((price * publisher.rental)/100) %></b></div>
			<div class="clear"></div>
			<div class="add_to_cart">Add to Cart</div>
		</div>
	</div>
	<div class="right">
		<div class="information">
			<div class="information_left">ISBN10:</div>
			<div class="information_right"><%%= isbn10 %></div>
			<div class="clear"></div>
			<div class="information_left">ISBN13:</div>
			<div class="information_right"><%%= isbn13 %></div>
			<div class="clear"></div>
			<div class="information_left">binding:</div>
			<div class="information_right"><%%= binding %></div>
			<div class="clear"></div>
			<div class="information_left">publisher:</div>
			<div class="information_right"><%%= publisher.name %></div>
			<div class="clear"></div>
			<div class="information_left">published:</div>
			<div class="information_right"><%%= published %></div>
			<div class="clear"></div>
			<div class="information_left">pages</div>
			<div class="information_right"><%%= pages %></div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="clear"></div>
	<div class="text"> 
		<div class="text_left">Description</div>
		<div class="text_right"><%%= description || "--" %></div>
		<div class="clear"></div>
	</div>
	<!--<div class="text"> 
		<div class="text_left">Strengths</div>
		<div class="text_right"><%%= strengths || "--" %></div>
		<div class="clear"></div>
	</div>
	<div class="text"> 
		<div class="text_left">Weaknesses</div>
		<div class="text_right"><%%= weaknesses || "--" %></div>
		<div class="clear"></div>
	</div>-->

	<div class="reviews_box">
		<div class="reviews_caption">
			<div class="reviews_caption_left">User Reviews</div>

			<% if current_user %>			
				<div class="reviews_caption_right">Leave a Review</div>
			<% end %>

			<div class="clear"></div>
		</div>
		<div class="reviews">
			<div class="reviews_content"></div>

			<% if current_user %>
				<form class="reviews_form">
					<input type="text" class="reviews_input" id="review_semester" placeholder="Write your Semester Eg: 1">
					<textarea placeholder="Write a review" id="review_text_content" class="reviews_input"></textarea><br/>
					<button type="submit" class="btn reviews_submit">Submit</button>
				</form>
			<% end %>
		</div>

	</div>
</script>

app/views/home/_footer.html.erb
<div class="footer">
	<div class="wrapper">
		<div class="right links">
			<div class="grid_1">
				<ul class="left">
					<li><a href="#terms_of_use_page" class="static_page_dialog_open">Terms of Use</a></li>
					<li><a href="#privacy_policy_page" class="static_page_dialog_open">Privacy Policy</a></li>
					<li><a href="#contact_us_page" class="static_page_dialog_open">Contact Us</a></li>
				</ul>
				<ul class="left">
					<li><a href="#about_us_page" class="static_page_dialog_open">About Us</a></li>
					<li><a href="#pricing_page" class="static_page_dialog_open">FAQ</a></li>
					<li><a href="#colleges_page" class="static_page_dialog_open">College ambassadors</a></li>
				</ul>
			</div>
		</div>
		<div class="foot_box left">
			<ul>
				<li><a class="fb" href="http://www.facebook.com/sociorent" target="_blank"></a></li>
				<li><a class="twit" href="http://www.twitter.com/sociorent" target="_blank"></a></li>
				<li><a class="blog" href="http://sociorent.com/blog" target="_blank"></a></li>
			</ul>
		</div>
		<div class="cB"></div>
	</div>
</div>
<div class="footer_cpy">
	<div class="wrapper">
		<span>&copy; Sociorent. All rights reserved.</span>
	</div>
</div>

<div id="book_details" class="font-dialog"></div>

app/views/home/_index_template.html.erb
<script type="script/template" id="search_template">
	<div class="book_left">
		<img src='<%%= image %>'/>
	</div>
	<div class="book_right">
		<div class="name" title="<%%= name %>"><%%= name %></div>
		<div class="author"><i>by</i> - <%%= author %></div>
		<div class="mrp">MRP: Rs.<%%= mrp %></div>
		<div class="rent_price">Rent @ Rs.<%%= rent_price %></div>
		<div class="add_to_cart"><%%= cart_message %></div>
	</div>
	<div class="clear"></div>
</script>

<script type="script/template" id="book_details_template">
	<div class="book_heading"><%%= name %> <small><i>by</i> <%%= author %></small></div>
	<div class="left">
		
		<div class="book_image">
			<img src="<%%= book_image %>"/>
		</div>	
		<div class="auther_edition">
			<div class="edition"><b><%%= edition %></b></div>
			<div class="author">Author(s): <p><span class="blue author_names"></span></p></div>
		</div>
		<div class="clear"></div>
		
		<!--<div class="socio_rent_rank">
			<div class="socio_rent_rank_left">
				SocioRent Rank
			</div>
			<div class="socio_rent_rank_right">
				<span class="blue"><%%= rank %>%</span>
			</div>
			<div class="clear"></div>
		</div>-->

	</div>
	<div class="right">
		<div class="information information_price">
			<div class="information_left"><b>list price</b></div>
			<div class="information_right"><b>Rs.<%%= price %></b></div>
			<div class="clear"></div>
			<div class="information_left"><b>rent</b></div>
			<div class="information_right"><b>Rs.<%%= ((price * publisher.rental)/100).toFixed(0) %></b></div>
			<div class="clear"></div>
			<div class="add_to_cart btn">Add to Cart</div>
		</div>
	</div>
	<div class="right">
		<div class="information">
			<div class="information_left">ISBN10:</div>
			<div class="information_right"><%%= isbn10 %></div>
			<div class="clear"></div>
			<div class="information_left">ISBN13:</div>
			<div class="information_right"><%%= isbn13 %></div>
			<div class="clear"></div>
			<div class="information_left">binding:</div>
			<div class="information_right"><%%= binding %></div>
			<div class="clear"></div>
			<div class="information_left">publisher:</div>
			<div class="information_right"><%%= publisher.name %></div>
			<div class="clear"></div>
			<div class="information_left">published:</div>
			<div class="information_right"><%%= published %></div>
			<div class="clear"></div>
			<div class="information_left">pages</div>
			<div class="information_right"><%%= pages %></div>
			<div class="clear"></div>
		</div>
	</div>
	<div class="clear"></div>
	<div class="text"> 
		<div class="text_left">Description</div>
		<div class="text_right"><%%= description || "--" %></div>
		<div class="clear"></div>
	</div>
	<!--<div class="text"> 
		<div class="text_left">Strengths</div>
		<div class="text_right"><%%= strengths || "--" %></div>
		<div class="clear"></div>
	</div>
	<div class="text"> 
		<div class="text_left">Weaknesses</div>
		<div class="text_right"><%%= weaknesses || "--" %></div>
		<div class="clear"></div>
	</div>-->

	<div class="reviews_box">
		<div class="reviews_caption">
			<div class="reviews_caption_left">User Reviews</div>
			
			<% if current_user %>
				<div class="reviews_caption_right">Leave a Review</div>
			<% end %>

			<div class="clear"></div>
		</div>
		<div class="reviews">
			<div class="reviews_content"></div>
		</div>
	</div>
</script>


<script type="script/template" id="review_template">
	<div class="review_single_left"><%%= user.name %></div>
	<div class="review_single_right"><%%= content %></div>
	<div class="clear"></div>
</script>

app/views/home/_review_template.html.erb
<script type="script/template" id="review_template">
<div class="review_single">
	<div class="review_single_left"><%%= user.name %></div>
	<div class="review_single_right"><%%= content %></div>
	<div class="clear"></div>

</div>
</script>

app/views/home/book.html.erb
<html>
  <head prefix="og: http://ogp.me/ns# fb: http://ogp.me/ns/fb# sociorent: http://ogp.me/ns/fb/sociorent#">
    <meta property="fb:app_id" content="212611612202812" /> 
    <meta property="og:type"   content="sociorent:book" /> 
    <meta property="og:url"    content="http://www.sociorent.com/book/detail/<%= @book.id %>" /> 
    <meta property="og:title"  content="<%= @book.name %>" /> 
    <meta property="og:image"  content="<%= @book_image %>" />
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
  </head>
  <body>
    <div><%= @book.name %></div>
  </body>
  <script type="text/javascript">
    $(window).load(function(){
      window.location.href = "http://www.sociorent.com/?isbn=<%= @book.isbn10 %>";
    });
  </script>
</html>

app/views/home/counter.html.erb
<h3>Counter for <%= @counter.college.name %></h3>
<% @counter.college.orders.where(:order_type => "cash", :payment_done => false).each do |order| %>
	<div>
		<div>Order Number: <%= order.random %></div>
		<div>Order Amount: <%= order.total %></div>
		<a href="#" id="order_<%= order.id %>" class="order_confirm">Click to confirm reciept of amount</a>
	</div>
	<br/>
<% end %>

<br/>
<div><%= link_to "SignOut", destroy_counter_session_path, :method => :delete %></div>

<script type="text/javascript">
	$(document).ready(function(){
		$(".order_confirm").click(function(){
			var that = this;
			var order_id = this.id.replace("order_", "");
			var c = confirm("Confirm");
			if(c){
				$.ajax("/orders/counter_cash_payment", {
					type:"post",
					async:true,
					data: {
						order_id: order_id
					},
					success: function(msg){
						if(msg.status == 1)
							$(that).parent().fadeOut(200);
//						alert(msg.msg);
					}
				});
			}
			return false;
		});
	});
</script>